### ISSUE TITLE
issue with `download_data` methods in `api.py`

### ISSUE THREAD

**Issue by anandi1989** [uuazed/crunchdao#3]
`download_data`  methods in  `api.py` throwing error 

` def download_data(self, directory: str = ".") -> list[str]:`

`TypeError: 'type' object is not subscriptable`

Above issue is fixed by replacing 

from - 
`def download_data(self, directory: str = ".") -> list[str]:`
to - 
`def download_data(self, directory: str = ".") -> List[str]:`

Note: I already fixed this in my local. Will raise pull requests for the same if required

**Comment by uuazed** [comment]
The library was build for Python3.9 and above, where using `from typing import List` is no longer needed. Checkout https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections. Apparently you are using some older Python version.

**Comment by anandi1989** [comment]
Thanks for pointing out and you’re right I am using `Python 3.8`. So, I had to edit the source code to work this package smoothly. Wouldn’t it be nice to have this package compatible with `Python 3.x` in general. Just a consumer thought! 

Thanks!

**Comment by uuazed** [comment]
Good suggestion! Version 0.1.3 now allows Python versions >=3.7.1

**Comment by anandi1989** [comment]
> Good suggestion! Version 0.1.3 now allows Python versions >=3.7.1

Awesome! Happy Crunching
